### ISSUE TITLE
yarn lint is not working for 5.9.3 version

### ISSUE THREAD

**Issue by patil-akshay** [okta/okta-signin-widget#2154]
:information_source: **If you have a question**, please post it on the [Okta Developer Forum](https://devforum.okta.com) instead. Issues in this repository are reserved for bug reports and feature requests.

### I'm submitting a
  - [ 1] bug report
  - [ ] feature request

### Background info

babel-eslint has been deprecated recently which is causing lint failure when we are trying to run yarn lint.
Error details:

```
RangeError: Maximum call stack size exceeded
    at Object.resolve (path.js:973:10)
    at createContext (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/config-array-factory.js:372:16)
    at ConfigArrayFactory.loadInDirectory (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/config-array-factory.js:490:25)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/okta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/Users/pakshay/Desktop/-kta-signin-widget/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:398:20)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "lint:eslint" exited with 2.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

### Expected behavior

yarn lint should work fine without throwing any erros

### What went wrong?

Please provide log or error messages if applicable.

### Steps to reproduce

If the current behavior is a bug, please provide the steps to reproduce and a minimal demo if possible (you can use this template as a starting point: https://jsfiddle.net/m2gyLq4v/).

### Your environment

  - Okta Sign-In Widget Version: 5.9.3
  - Browser: chrome
  - OS:Mac
  - Language:English

**Comment by shuowu** [comment]
@patil-akshay can you try the latest version 5.9.4? The `yarn lint` command works well in my local env.
If it still not work for you, probably try remove `node_modules` from the root folder, then start a brand new `yarn install`.

Technically, `yarn lint` should not fail, as it's running in the CI system, if it fails that specific version cannot be released.

**Comment by patil-akshay** [comment]
@shuowu 5.9.4 has only changes in readme & package.json file not sure How it will help to solve the issue.
