### ISSUE TITLE
Okta widget not loadding

### ISSUE THREAD

**Issue by raghuvarbisht** [okta/okta-signin-widget#2542]
### Describe the bug

Hi Team,

I am using Okta sign-in a widget from long for our quasar app(vuejs) based single-page application.
Suddenly we are getting a blank screen and below error in the console when opening the application in the browser.

Uncaught Error: Your client ID is missing. You can copy it from the Okta Developer Console in the details for the Application you created. Follow these instructions to find it: https://bit.ly/finding-okta-app-credentials
    at new t (vendor.4ef7a263.js:147:359)
    at o.assertClientId (vendor.4ef7a263.js:147:2437)
    at new e (vendor.4ef7a263.js:172:138)
    at Object.install (vendor.4ef7a263.js:195:21)
    at Function.Tr.e.use (vendor.4ef7a263.js:68:35541)
    at Module.2f39 (app.0f5283cc.js:1:851234)
    at r (app.0f5283cc.js:1:562)
    at Object.0 (app.0f5283cc.js:1:1562)
    at r (app.0f5283cc.js:1:562)
    at i (app.0f5283cc.js:1:431)

<img width="935" alt="login page" src="https://user-images.githubusercontent.com/16816187/170464169-9853ca93-7bc4-4b97-b9d1-4be4627ae93f.png">

### What is expected to happen?

It should show okta login widget.

### What is the actual behavior?

Show the Okta login screen 

### Reproduction Steps

<img width="935" alt="login page" src="https://user-images.githubusercontent.com/16816187/170464501-70801595-3ae8-4409-99ac-78c11496302e.png">

### SDK Versions

"@okta/okta-auth-js": "^5.2.3",
    "@okta/okta-signin-widget": "4.4.4",
    "@okta/okta-vue": "2.1.1",

### Execution Environment

Framework- Quasar app (Vuejs)
Language - Javascript
Server- Ngnix

**Comment by raghuvarbisht** [comment]
Issue resolved now
