### ISSUE TITLE
No remediation can match current flow, check policy settings in your org. Remediations: [select-authenticator-unlock-account]

### ISSUE THREAD

**Issue by dpgbt** [okta/okta-signin-widget#3503]
### Describe the bug

No remediation can match current flow, check policy settings in your org. Remediations: [select-authenticator-unlock-account]

### Reproduction Steps

Prepare SPA.
Enter locked email address and Press Next button. 
Next button is spinning/loading without a response.

When debug, the error message in debug variables...

Using 
<script src="https://global.oktacdn.com/okta-signin-widget/7.14.0/js/okta-sign-in.polyfill.min.js" type="text/javascript"></script>
<script src="https://global.oktacdn.com/okta-signin-widget/7.14.0/js/okta-sign-in.oie.min.js" type="text/javascript"></script>
<link href="https://global.oktacdn.com/okta-signin-widget/7.14.0/css/okta-sign-in.min.css" type="text/css" rel="stylesheet"/>

We do see this error:

FormController.ts:387 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'messages')
    at FormController.ts:387:82
    at f (FormController.ts:2:1)
    at Generator.<anonymous> (FormController.ts:2:1)
    at Generator.next (FormController.ts:2:1)
    at O (FormController.ts:2:1)
    at a (FormController.ts:2:1)
    at FormController.ts:2:1
    at new Promise (<anonymous>)
    at FormController.ts:2:1
    at G.r.showFormErrors (FormController.ts:360:44)

### SDK Versions

Tried 7.12.2,  7.13.1 and 7.14.0

**Comment by adhir-chakravarti** [comment]
I experienced a very similar error, the only difference for me was the remediation.

```
No remediation can match current flow, check policy settings in your org. Remediations: [reset-authenticator]
```

The solution for me was to remove the "flow" prop from the okta-config object as described here:  https://support.okta.com/help/s/article/Error-in-the-Password-Widget-flow-for-the-selfhosted-Okta-Signin-widget-enabled-with-Interaction-Code-flow?language=en_US
