### ISSUE TITLE
OktaSignInWidget breaks React Jest/Enzyme testing

### ISSUE THREAD

**Issue by Fieel** [okta/okta-signin-widget#935]
Hello, I wrote about this issue [on the forums](https://devforum.okta.com/t/oktasigninwidget-breaks-react-jest-enzyme-testing/6608) with no luck, so here I am:

### I'm submitting a
  - [x] bug report
  - [ ] feature request

### Background info

I found that OktaSignInWidget breaks my Jest/Enzyme tests in my React SPA. This has been halting my tests development for two days now so I really need some help here :frowning:

If I try to render my App component which imports a custom SignInComponent who simply imports and renders the OktaSignInPlugin.

### Expected behavior

The test passes and the OktaSignInWidget is rendered.

### What went wrong?

OktaSignInPlugin crashes whenever a component who implements it is used.  The error is because of a null prop, in this case, ‘backingStorePixelRatio’. Error:

```
FAIL  src/App.test.js

● Test suite failed to run

TypeError: Cannot read property 'backingStorePixelRatio' of null

  1 | import React, { Component } from 'react';
  2 | import ReactDOM from 'react-dom';
> 3 | import OktaSignIn from '@okta/okta-signin-widget';
    | ^
  4 | import '@okta/okta-signin-widget/dist/css/okta-sign-in.min.css';
  5 | 
  6 | class SignInWidget extends Component {

  at node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/qtip2/dist/jquery.qtip.min.js:3:26873
  at Object.<anonymous> (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/qtip2/dist/jquery.qtip.min.js:3:27024)
  at node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/qtip2/dist/jquery.qtip.min.js:3:101
  at node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/qtip2/dist/jquery.qtip.min.js:3:138
  at Object.<anonymous> (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/qtip2/dist/jquery.qtip.min.js:4:12128)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:19:1)
  at Object.require (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:4428:18)
  at call (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:22:30)
  at Object.__webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:9089:63)
  at call (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:22:30)
  at Object.__webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:7593:79)
  at call (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:22:30)
  at Object.__webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:5238:17)
  at call (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:22:30)
  at Object.__webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:5144:18)
  at call (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:22:30)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:65:18)
  at Object.<anonymous> (node_modules/@okta/okta-signin-widget/dist/js/webpack:/packages/@okta/courage-dist/okta.js:3:10)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:19:1)
  at Object.ceil (node_modules/@okta/okta-signin-widget/dist/js/webpack:/src/util/OAuth2Util.js:13:9)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:19:1)
  at require (node_modules/@okta/okta-signin-widget/dist/js/webpack:/src/widget/OktaSignIn.js:7:20)
  at Object.<anonymous> (node_modules/@okta/okta-signin-widget/dist/js/webpack:/src/widget/OktaSignIn.js:3:18)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:19:1)
  at Object.<anonymous> (node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js:32109:18)
  at __webpack_require__ (node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:19:1)
  at node_modules/@okta/okta-signin-widget/dist/js/webpack:/webpack/bootstrap 4daf3bea66f1545a0639:62:1
  at node_modules/@okta/okta-signin-widget/dist/js/okta-sign-in.entry.js:76:10    
  at webpackUniversalModuleDefinition (node_modules/@okta/okta-signin-widget/dist/
```

![5946853e5d83f8d120b703b1276c1c59284b89a6](https://user-images.githubusercontent.com/11167635/67760499-be0f4200-fa41-11e9-86d4-5620c55d6c26.png)

### Steps to reproduce

Create a basic react app with create-react-app add the SignInWidget to the login page and run the most basic test ever, such as (provided by create-react-app by default) this one: 

```
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';

 describe('App.js component', () =>{
    it('renders without crashing', () => {
      const div = document.createElement('div');
      ReactDOM.render(<App />, div);
      ReactDOM.unmountComponentAtNode(div);
    });
 })
```

### Your environment

  - Okta Sign-In Widget Version: ^3.2.1
  - Browser: no one. Tests don't run on the browser.
  - OS: Windows 10.
  - Language: JS, it's a react app, using create-react-app.

**Comment by holdtb** [comment]
If you want a workaround, you can just mock the signin widget entirely. 

Assumptions:
1. You copied their React component that wraps the '@okta/OktaSignInWidget' module
2. You do not need to interact with the widget in your test (ie you trust the widget okta provides is fully functional)

In my case, my wrapper component is located at the path seen below, swap out the path for what makes sense in your project

`jest.mock('./Login/OktaSignInWidget.tsx', () => {
  return <div>SignIn</div>;
});`

**Comment by Fieel** [comment]
Perfect! For some reason i thought mocking ES6 module imports was more difficult in Jest that this.

This is my line:

```
jest.mock("./components/auth/SignInWidget", () => {
  return <div>SignInWidgetMock</div>;
});
```

**Comment by swiftone** [comment]
@Fieel - thanks for the report.  The error message can be misleading - in this case we're pretty sure the issue is that the widget assumes a browser environment, which jest is not (by itself).

You could run your tests in a browser environment like karma, possibly mock the browser in jest using jsdom, etc, or mock out the widget in your tests (as @holdtb recommends, thanks!).  I'd recommend the latter, as a matter of isolating what you're testing, and leave the browser testing for full end-to-end acceptance testing.

**Comment by Fieel** [comment]
@swiftone Thank you for the heads-up!

I'm not testing browser-specific behavior so mocking the widget entirely is perfect for me.

I'm closing the issue as it's actually resolved
